/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aboutpage: typeof import('./resources/js/components/aboutpage.vue')['default']
    AddDialog: typeof import('./resources/js/components/dialogs/AddDialog.vue')['default']
    AppointmentTable: typeof import('./resources/js/components/AppointmentTable.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DeleteConfirmationDialog: typeof import('./resources/js/components/DeleteConfirmationDialog.vue')['default']
    DeleteDialog: typeof import('./resources/js/components/dialogs/DeleteDialog.vue')['default']
    DialogManager: typeof import('./resources/js/components/DialogManager.vue')['default']
    EditDialog: typeof import('./resources/js/components/dialogs/EditDialog.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Header: typeof import('./resources/js/components/header.vue')['default']
    Homepage: typeof import('./resources/js/components/homepage.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    UseraddDialog: typeof import('./resources/js/components/dialogs/useraddDialog.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
